# Meta Data for SEO

## Homepage
title = "site"
titleSeparator = "-"
titleAddition = "Modern Hugo Starter"
description = "tanım işte site tanımı."

## Open Graph
images = ["hyas.png"]
ogLocale = "en_US"
titleHome = "Hyas Hugo Starter"

## Twitter Cards
twitterSite = "@gethyas"
twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Hyas"
schemaAuthor = "Cem Kaan KÖSALI"
schemaAuthorTwitter = " twitter.com/kaanguru2"
schemaAuthorLinkedIn = "https://linkedin.com/in/cemkaan/"
schemaAuthorGitHub = "https://github.com/cemkaan"
schemaLocale = "tr"
schemaLogo = "logo-hyas.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "hyas.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/kaanguru2"
schemaLinkedIn = ""
<<<<<<< HEAD
schemaGitHub = "https://github.com/h-enk/hyas"
=======
schemaGitHub = "https://github.com/cemkaan/hyas"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false
>>>>>>> d82e82fafedf99ca2ec7e1dee7a6dc6801a0137e

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

# Footer
<<<<<<< HEAD
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://gethyas.com/\">Hyas</a>"

# Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Alert
alert = true
alertDismissable = true
alertText = "Deliver web projects 10x faster. <a class=\"alert-link\" href=\"https://www.netlify.com/whitepaper/\" target=\"_blank\" rel=\"noopener\">Get the free enterprise paper →</a>"
=======
footer = """ Web Tasarım <a href="https://cemkaan.com/" target="_blank" >CemKaan.com</a> """ 
copyRight = "Copyright (c) 2021 Cem Kaan"

# Alert
alert = false
alertText = "Deliver web projects 10x faster. "
>>>>>>> d82e82fafedf99ca2ec7e1dee7a6dc6801a0137e
